onlineStore/config/routes.rb
Rails.application.routes.draw do
  get 'search/index'
  post 'search/index', to: 'search#index'
  get 'navs/faq'
  get 'navs/news'
  get 'navs/contact'
  get 'navsfaq/news'
  get 'navsfaq/contact'
  get 'access/new'
  post 'access/new', to: 'access#create'
  get 'access/create'
  get 'access/destroy'
  get 'admin/index'
  resources :users
  resources :orders
  resources :lineitems 
  resources :carts
  get 'shopper/index' #goes to shopper#index action
  # get '/', to: "shopper#index"
  root "shopper#index", as: 'shopper' #shopper_url, showpper_path
  resources :products #new_product_path, new_product_url
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get '/shopper', to: 'shopper#index'
  get '/admin', to: 'admin#index'
  get '/login', to: 'access#new'
  post '/login', to: 'access#create'
  get '/logout', to: 'access#destroy'
  post '/logout', to: 'access#destroy'
  # Defines the root path route ("/")
  # root "articles#index"
end

onlineStore/app/models/order.rb
class Order < ApplicationRecord
    has_many(:lineitems, dependent: :destroy)
    PAYMENT_TYPES = ["Check", "Credit Card", "Venmo", "Paypal"]
    validates :name, :address, :email, presence: true
    validates :paytype, inclusion: PAYMENT_TYPES

    def add_items_from_cart(cart)
        cart.lineitems.each do |item|
          item.cart_id = nil
          item.order_id = self.id
        end
      end
end

onlineStore/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  # skip_before_action :authorize
  include CurrentCart
  before_action :set_cart 
  before_action :set_order, only: %i[ show edit update destroy ]

  # GET /orders or /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1 or /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    if @cart.lineitems.empty?
      redirect_to shopper_url, notice: "Your cart is empty"
      return
    end
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders or /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        Cart.destroy(session[:cart_id])
        session[:cart_id] = nil
        format.html { redirect_to shopper_url(@order), notice: "Thank you for your order." }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1 or /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to order_url(@order), notice: "Order was successfully updated." }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1 or /orders/1.json
  def destroy
    @order.delete

    respond_to do |format|
      format.html { redirect_to orders_url, notice: "Order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(:name, :address, :email, :paytype)
    end
end

onlineStore/app/helpers/orders_helper.rb
module OrdersHelper
end

onlineStore/app/views/orders/_form.html.erb
<%= form_for(@order) do |form| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, size: 40 %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_area :address, row: 3, cols: 40 %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, size: 40 %>
  </div>

  <div class="field">
    <%= form.label :paytype %>
    <%= form.select :paytype, Order::PAYMENT_TYPES, prompt: 'Select a payment method' %>
  </div>

  <div class="actions">
    <%= form.submit 'Place Order'%>
  </div>
<% end %>

onlineStore/app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

onlineStore/app/views/orders/index.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Email</th>
      <th>Paytype</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.name %></td>
        <td><%= order.address %></td>
        <td><%= order.email %></td>
        <td><%= order.paytype %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, :method => :delete, data: { :confirm => 'Are you sure?' } , :title => "Delete #{order.name}"%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

onlineStore/app/views/orders/new.html.erb
<h1>New Order</h1>

<div class="order_form">
  <fieldset>
    <legend>Please Enter Your Info</legend>
    <%= render 'form' %>
  </fieldset>
<%= link_to 'Back', shopper_path %>

onlineStore/app/views/orders/show.html.erb
<%if notice %>
<p id="notice"><%= notice %></p>
<% end %>

<p>
  <strong>Name:</strong>
  <%= @order.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @order.address %>
</p>

<p>
  <strong>Email:</strong>
  <%= @order.email %>
</p>

<p>
  <strong>Paytype:</strong>
  <%= @order.paytype %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>