onlineStore/config/routes.rb
Rails.application.routes.draw do
  get 'search/index'
  post 'search/index', to: 'search#index'
  get 'navs/faq'
  get 'navs/news'
  get 'navs/contact'
  get 'navsfaq/news'
  get 'navsfaq/contact'
  get 'access/new'
  post 'access/new', to: 'access#create'
  get 'access/create'
  get 'access/destroy'
  get 'admin/index'
  resources :users
  resources :orders
  resources :lineitems 
  resources :carts
  get 'shopper/index' #goes to shopper#index action
  # get '/', to: "shopper#index"
  root "shopper#index", as: 'shopper' #shopper_url, showpper_path
  resources :products #new_product_path, new_product_url
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get '/shopper', to: 'shopper#index'
  get '/admin', to: 'admin#index'
  get '/login', to: 'access#new'
  post '/login', to: 'access#create'
  get '/logout', to: 'access#destroy'
  post '/logout', to: 'access#destroy'
  # Defines the root path route ("/")
  # root "articles#index"
end

onlineStore/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OnlineStore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "application", 'data-turbolinks-track': 'reload' %>
  </head>

  <body class='<%= controller.controller_name %>'>

    <div id="banner">
      <%= @page_title || "Our Products" %>
      <p>
        Please use the following username and password to test this application
      </p>
      <p>
        user name: assignment4
        <br />
        password: newpassword
      </p>
    </div>

    <div id="columns">
    <div id="side">
      <div id='cart'>
        <%= render @cart%>
      </div>
      <ul>
        <li><a href="/shopper">Home</a></li>
        <li><a href="/navs/faq">Questions</a></li>
        <li><a href="/navs/news">News</a></li>
        <li><a href="/navs/contact">Contact</a></li>
        <li><a href="/search/index">Search</a></li>
        <%= button_to 'Login', login_path%>
      </ul>
      <% if session[:user_id] %>
        Hello, <%= User.find_by(id: session[:user_id]).name%>
        <ul>
          <li><%= link_to 'Orders',orders_path %></li>
          <li><%= link_to 'Products', products_path %></li>
          <li><%= link_to 'Users',    users_path    %></li>
        </ul>
        <%= button_to 'Logout', logout_path%>
      <% end %>
    </div>
    <div id="main">
      <%= yield %>
    </div>
  </div>

  </body>
</html>